-- Add landing_page to the blogs.content_type CHECK constraint
-- Run this in the Supabase SQL Editor.

-- 1. Drop the existing constraint (name is auto-generated by Postgres)
ALTER TABLE blogs DROP CONSTRAINT IF EXISTS blogs_content_type_check;

-- 2. Re-add it with landing_page included
ALTER TABLE blogs
  ADD CONSTRAINT blogs_content_type_check
  CHECK (content_type IN ('blog', 'ebook', 'whitepaper', 'linkedin', 'landing_page'));
